export const products = [
  {
    ASIN: "B077MLYR24",
    title:
      "PUMA SMASH V2 L, Zapatillas Deportivas Unisex adulto, Blanco (White Black), 42 EU",
    price: "32,95\u00a0\u20ac",
    listPrice: "54,95\u00a0\u20ac",
    imageUrl: "https://m.media-amazon.com/images/I/317XR8ULtGL._SL160_.jpg",
    detailPageURL: "https://www.amazon.es/dp/B077MLYR24",
    rating: "4.4",
    totalReviews: "74897",
    subtitle: "",
    isPrimeEligible: "1",
  },
  {
    ASIN: "B09NP3SGW2",
    title: "DC Shoes Pure, Zapatillas Hombre, Black/Gum, 44 EU",
    price: "53,70\u00a0\u20ac",
    listPrice: "90,00\u00a0\u20ac",
    imageUrl: "https://m.media-amazon.com/images/I/31fDR-w+HvL._SL160_.jpg",
    detailPageURL: "https://www.amazon.es/dp/B09NP3SGW2",
    rating: "4.6",
    totalReviews: "717",
    subtitle: "",
    isPrimeEligible: "1",
  },
  {
    ASIN: "B07ZK5Q7ZB",
    title: "Munich Dash 2023, Zapatillas para Unisex adulto, Gris 24, 38 EU",
    price: "68,00\u00a0\u20ac",
    listPrice: "",
    imageUrl: "https://m.media-amazon.com/images/I/415t4QPdw1L._SL160_.jpg",
    detailPageURL: "https://www.amazon.es/dp/B07ZK5Q7ZB",
    rating: "4.3",
    totalReviews: "1190",
    subtitle: "",
    isPrimeEligible: "1",
  },
  {
    ASIN: "B0BNJ3G1NM",
    title:
      "Kappa C\u00f3digo de Estilo: 243362 Sedley, Zapatillas de Deporte Unisex adulto, Blanco, 44 EU",
    price: "34,65\u00a0\u20ac",
    listPrice: "",
    imageUrl: "https://m.media-amazon.com/images/I/41ab3tUf5xL._SL160_.jpg",
    detailPageURL: "https://www.amazon.es/dp/B0BNJ3G1NM",
    rating: "4.0",
    totalReviews: "17",
    subtitle: "",
    isPrimeEligible: "1",
  },
  {
    ASIN: "B09692P25W",
    title:
      "Under Armour UA Charged Pursuit 3, Zapatillas para Correr Hombre, Mod Gray/Mod Gray/Black, 45 EU",
    price: "50,44\u00a0\u20ac",
    listPrice: "65,00\u00a0\u20ac",
    imageUrl: "https://m.media-amazon.com/images/I/31W17VK7pEL._SL160_.jpg",
    detailPageURL: "https://www.amazon.es/dp/B09692P25W",
    rating: "4.4",
    totalReviews: "1800",
    subtitle: "",
    isPrimeEligible: "1",
  },
  {
    ASIN: "B01DWP49EW",
    title: "Puma Tazon 6 FM, Zapatillas de Running Hombre, White/Silver, 41 EU",
    price: "60,44\u00a0\u20ac",
    listPrice: "112,47\u00a0\u20ac",
    imageUrl: "https://m.media-amazon.com/images/I/413Y+DxwPLL._SL160_.jpg",
    detailPageURL: "https://www.amazon.es/dp/B01DWP49EW",
    rating: "4.5",
    totalReviews: "56254",
    subtitle: "",
    isPrimeEligible: "1",
  },
  {
    ASIN: "B07F2Q511B",
    title:
      "PUMA Women's Fashion Shoes CILIA Trainers & Sneakers, PUMA WHITE-GRAY VIOLET-PUMA SILVER, 39",
    price: "34,60\u00a0\u20ac",
    listPrice: "64,95\u00a0\u20ac",
    imageUrl: "https://m.media-amazon.com/images/I/21LBJBVHPYL._SL160_.jpg",
    detailPageURL: "https://www.amazon.es/dp/B07F2Q511B",
    rating: "4.6",
    totalReviews: "8743",
    subtitle: "",
    isPrimeEligible: "0",
  },
  {
    ASIN: "B077MFV793",
    title:
      "PUMA Unisex Adults' Sport Shoes NRGY COMET Road Running Shoes, PUMA BLACK-PUMA WHITE, 44.5",
    price: "26,45\u00a0\u20ac",
    listPrice: "59,95\u00a0\u20ac",
    imageUrl: "https://m.media-amazon.com/images/I/41AQ3JTmGmL._SL160_.jpg",
    detailPageURL: "https://www.amazon.es/dp/B077MFV793",
    rating: "4.4",
    totalReviews: "7190",
    subtitle: "",
    isPrimeEligible: "0",
  },
  {
    ASIN: "B0CBKMSFGX",
    title:
      "SAGUARO Zapatillas Minimalistas Unisex Punto Zapatos Descalzos Casuales Transpirable y Antideslizante Barefoot Calzado de Trail para Caminar Gimnasio, Negro Petr\u00f3leo, 38EU",
    price: "49,99\u00a0\u20ac",
    listPrice: "",
    imageUrl: "https://m.media-amazon.com/images/I/316kN4z3LPL._SL160_.jpg",
    detailPageURL: "https://www.amazon.es/dp/B0CBKMSFGX",
    rating: "4.2",
    totalReviews: "167",
    subtitle: "",
    isPrimeEligible: "1",
  },
  {
    ASIN: "B0835GB3X8",
    title:
      "DC Shoes Pure High-Top Elastic, Zapatillas Hombre, Black/Gum, 36 EU",
    price: "39,98\u00a0\u20ac",
    listPrice: "",
    imageUrl: "https://m.media-amazon.com/images/I/31J+IcjX8GL._SL160_.jpg",
    detailPageURL: "https://www.amazon.es/dp/B0835GB3X8",
    rating: "5.0",
    totalReviews: "35",
    subtitle: "",
    isPrimeEligible: "1",
  },
];
